---
title: "data605_hw14_wzhou"
author: "Wei Zhou"
date: "11/30/2019"
output: html_document
---

---
title: "DATA 605 Week 14 Homework"
author: "Ilya Kats"
date: "November 30, 2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, comment = NA, fig.align = 'center')
library(ggplot2)
```


##  $f(x) = \frac{1}{1-x}$ 

### Derivation

The first three derivatives for $f(x) = \frac{1}{1-x}$ are
$$f'(x) = \frac{1}{(1-x)^2} \\
f''(x) = \frac{2}{(1-x)^3} \\
f'''(x) = \frac{6}{(1-x)^4}$$

This can be generalized as
$$f^{(n)}(x) = \frac{n!}{(1-x)^{n+1}}$$

Substituting this into the general equation,
$$\frac{1}{1-x} \approx \sum_{n=0}^{\infty} \frac{n!}{(1-a)^{n+1}} \times \frac{(x-a)^n}{n!} = \frac{(x-a)^n}{(1-a)^n}$$

At $a=0$, this becomes
$$\frac{1}{1-x} \approx \sum_{n=0}^{\infty} x^n$$

#### Convergence
Using the ratio series for infinite series:
$$\frac{A_{n+1}}{A_n} = \frac{x^{n+1}}{x^n} = x \\
\lim_{n \to \infty} x = x$$

So the series converges for $|x| < 1$.

## $f(x) = e^x$ is $e^x$

### Derivation

The derivative of $f(x) = e^x$ is $e^x$, so any derivative $f^{(n)}(x) = e^x$.

Substituting this into the general equation,

$$e^x \approx \sum_{n=0}^{\infty} e^x \times \frac{(x-a)^n}{n!} = \frac{e^x (x-a)^n}{n! (1-a)^n}$$

At $a=0$, this becomes
$$\frac{1}{1-x} \approx \sum_{n=0}^{\infty} \frac{x^n}{n!}$$

#### Convergence
Using the ratio series for infinite series:
$$\frac{A_{n+1}}{A_n} = \frac{x^{n+1}}{(n+1)!} \frac{n!}{x^n} = \frac{x}{n+1} \\
\lim_{n \to \infty} \frac{x}{n+1} = 0$$

So the series converges for all values of x.



## $f(x) = e^x$ is $e^x$

### Derivation

The first four derivatives for $f(x) = \ln(x)$ are
$$f^{(1)}(x) = \frac{1}{1+x} \\
f^{(2)}(x) = \frac{-1}{(1+x)^2} \\
f^{(3)}(x) = \frac{2}{(1+x)^3} \\
f^{(4)}(x) = \frac{-6}{(1+x)^4}$$

This can be generalized as
$$f^{(n)}(x) = (-1)^{n-1} \frac{(n-1)!}{(1+x)^{n}}$$

Substituting this into the general equation,
$$\ln(1+x) \approx \sum_{n=0}^{\infty} (-1)^{n-1} \frac{(n-1)!}{(1+a)^{n}} \times \frac{(x-a)^n}{n!} = (-1)^{n-1} \frac{(x-a)^n}{n (1+a)^n}$$

At $a=0$, this becomes
$$\ln(1+x) \approx \sum_{n=0}^{\infty} (-1)^{n-1} \frac{x^n}{n}$$

#### Convergence
Using the ratio series for infinite series:
$$\frac{A_{n+1}}{A_n} = - \frac{x^{n+1}}{n} \frac{n}{x^n} = - \frac{-xn}{n+1} \\
\lim_{n \to \infty} \frac{-xn}{n+1} = -x$$

So the series converges for $|x| < 1$.

